baseDns: rhcl.ocp.acme.com
ingressDomain: apps.ocp.acme.com
rhclVersion: 1.4.0
helloWorldApp:
  oidc:
    enabled: true
  requestInterceptor:
    externalAuthorization:
      enabled: false
    requestMirror:
      enabled: false
metallb:
  ipAddressPool:
    addresses:
      - 192.168.1.240-192.168.1.250