---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-monitoring-config
  namespace: openshift-monitoring
  annotations:
    argocd.argoproj.io/sync-wave: "13"
data:
  config.yaml: |
    enableUserWorkload: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rhcl-observability
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "13"
spec:
  project: default
  source:
    repoURL: https://github.com/Kuadrant/kuadrant-operator
    targetRevision: v1.4.0
    path: config/install/configure/observability
  destination:
    server: https://kubernetes.default.svc
    namespace: gateway-system
  ignoreDifferences:
    - group: operators.coreos.com
      kind: Subscription
      name: grafana-operator
      namespace: openshift-operators
      jqPathExpressions:
        - .
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - SkipDryRunOnMissingResource=true
      - RespectIgnoreDifferences=true
