---
apiVersion: v1
kind: Namespace
metadata:
  name: grafana
  annotations:
    argocd.argoproj.io/sync-wave: "18"
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: grafana-operator
  namespace: grafana
  annotations:
    argocd.argoproj.io/sync-wave: "19"
spec:
  upgradeStrategy: Default
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: grafana-operator
  namespace: grafana
  annotations:
    argocd.argoproj.io/sync-wave: "19"
spec:
  channel: v5
  installPlanApproval: Automatic
  name: grafana-operator
  source: community-operators
  sourceNamespace: openshift-marketplace
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: grafana
  namespace: grafana
  annotations:
    argocd.argoproj.io/sync-wave: "20"
    serviceaccounts.openshift.io/oauth-redirectreference.primary: '{"kind":"OAuthRedirectReference","apiVersion":"v1","reference":{"kind":"Route","name":"grafana-instance-route"}}'
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ocp-injected-certs
  namespace: grafana
  labels:
    config.openshift.io/inject-trusted-cabundle: "true"
  annotations:
    argocd.argoproj.io/sync-wave: "20"
---
apiVersion: v1
kind: Secret
metadata:
  name: grafana-proxy
  namespace: grafana
  annotations:
    argocd.argoproj.io/sync-wave: "20"
type: Opaque
stringData:
  session_secret: eYLm0QseKh92AKAWvveKOTGqRm2jOQHWCtqk2vQgcyU=
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: grafana-proxy
  annotations:
    argocd.argoproj.io/sync-wave: "20"
rules:
  - apiGroups:
      - authentication.k8s.io
    resources:
      - tokenreviews
    verbs:
      - create
  - apiGroups:
      - authorization.k8s.io
    resources:
      - subjectaccessreviews
    verbs:
      - create
---
apiVersion: authorization.openshift.io/v1
kind: ClusterRoleBinding
metadata:
  name: grafana-proxy
  annotations:
    argocd.argoproj.io/sync-wave: "20"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: grafana-proxy
subjects:
  - kind: ServiceAccount
    name: grafana
    namespace: grafana
---
apiVersion: v1
kind: Secret
metadata:
  name: grafana-sa-token
  namespace: grafana
  annotations:
    argocd.argoproj.io/sync-wave: "20"
    kubernetes.io/service-account.name: grafana
type: kubernetes.io/service-account-token
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: grafana-cluster-monitoring-view
  annotations:
    argocd.argoproj.io/sync-wave: "20"
subjects:
  - kind: ServiceAccount
    name: grafana
    namespace: grafana
roleRef:
  kind: ClusterRole
  name: cluster-monitoring-view
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: grafana.integreatly.org/v1beta1
kind: Grafana
metadata:
  name: grafana-instance
  namespace: grafana
  labels:
    dashboards: grafana
  annotations:
    argocd.argoproj.io/sync-wave: "21"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  serviceAccount:
    metadata:
      name: grafana
      annotations:
        serviceaccounts.openshift.io/oauth-redirectreference.primary: '{"kind":"OAuthRedirectReference","apiVersion":"v1","reference":{"kind":"Route","name":"grafana-instance-route"}}'
  client:
    preferService: true
  config:
    log:
      mode: console
      level: warn
    auth:
      disable_login_form: "True"
      disable_signout_menu: "True"
    auth.anonymous:
      enabled: "False"
    auth.basic:
      enabled: "False"
    auth.proxy:
      enabled: "True"
      auto_sign_up: "True"
      enable_login_token: "False"
      header_name: "X-Forwarded-User"
      header_property: username
      headers: "Name:X-Forwarded-User Email:X-Forwarded-Email"
  deployment:
    skipCreateAdminAccount: true
    spec:
      template:
        spec:
          serviceAccountName: grafana
          volumes:
            - name: grafana-tls
              secret:
                secretName: grafana-tls
            - name: grafana-proxy
              secret:
                secretName: grafana-proxy
            - name: ocp-injected-certs
              configMap:
                name: ocp-injected-certs
          containers:
            - name: grafana-proxy
              image: quay.io/openshift/origin-oauth-proxy
              args:
                - -provider=openshift
                - -pass-basic-auth=false
                - -https-address=:9091
                - -http-address=
                - -email-domain=*
                - -upstream=http://localhost:3000
                - -openshift-sar={"resource": "namespaces", "verb": "get"}
                - -openshift-delegate-urls={"/": {"resource": "namespaces", "verb": "get"}}
                - -tls-cert=/etc/tls/private/tls.crt
                - -tls-key=/etc/tls/private/tls.key
                - -client-secret-file=/var/run/secrets/kubernetes.io/serviceaccount/token
                - -cookie-secret-file=/etc/proxy/secrets/session_secret
                - -openshift-service-account=grafana
                - -openshift-ca=/etc/pki/tls/cert.pem
                - -openshift-ca=/var/run/secrets/kubernetes.io/serviceaccount/ca.crt
                - -openshift-ca=/etc/proxy/certs/ca-bundle.crt
                - -skip-auth-regex=^/metrics
              ports:
                - containerPort: 9091
                  name: https
              volumeMounts:
                - mountPath: /etc/tls/private
                  name: grafana-tls
                - mountPath: /etc/proxy/secrets
                  name: grafana-proxy
                - mountPath: /etc/proxy/certs
                  name: ocp-injected-certs
  service:
    metadata:
      annotations:
        service.beta.openshift.io/serving-cert-secret-name: grafana-tls
    spec:
      ports:
        - name: https
          port: 9091
          protocol: TCP
          targetPort: https
  route:
    spec:
      port:
        targetPort: https
      tls:
        termination: reencrypt
      to:
        kind: Service
        name: grafana-instance-service
        weight: 100
      wildcardPolicy: None
---
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  name: openshift-thanos
  namespace: grafana
  annotations:
    argocd.argoproj.io/sync-wave: "22"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  allowCrossNamespaceImport: false
  datasource:
    access: proxy
    editable: true
    isDefault: true
    jsonData:
      httpHeaderName1: Authorization
      timeInterval: 5s
      tlsSkipVerify: true
    name: Prometheus
    secureJsonData:
      httpHeaderValue1: 'Bearer ${token}'
    type: prometheus
    url: 'https://thanos-querier.openshift-monitoring.svc:9091'
  instanceSelector:
    matchLabels:
      dashboards: grafana
  resyncPeriod: 10m0s
  valuesFrom:
    - targetPath: secureJsonData.httpHeaderValue1
      valueFrom:
        secretKeyRef:
          key: token
          name: grafana-sa-token
---
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDashboard
metadata:
  name: app-developer-dashboard
  namespace: grafana
  annotations:
    argocd.argoproj.io/sync-wave: "23"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  instanceSelector:
    matchLabels:
      dashboards: grafana
  datasources:
    - inputName: DS_PROMETHEUS
      datasourceName: Prometheus
  grafanaCom:
    id: 21538
---
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDashboard
metadata:
  name: business-user-dashboard
  namespace: grafana
  annotations:
    argocd.argoproj.io/sync-wave: "23"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  instanceSelector:
    matchLabels:
      dashboards: grafana
  datasources:
    - inputName: DS_PROMETHEUS
      datasourceName: Prometheus
  grafanaCom:
    id: 20981
---
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDashboard
metadata:
  name: platform-engineer-dashboard
  namespace: grafana
  annotations:
    argocd.argoproj.io/sync-wave: "23"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  instanceSelector:
    matchLabels:
      dashboards: grafana
  datasources:
    - inputName: DS_PROMETHEUS
      datasourceName: Prometheus
  grafanaCom:
    id: 20982
---
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDashboard
metadata:
  name: dns-operator-dashboard
  namespace: grafana
  annotations:
    argocd.argoproj.io/sync-wave: "23"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  instanceSelector:
    matchLabels:
      dashboards: grafana
  datasources:
    - inputName: DS_KUADRANT-THANOS-HUB
      datasourceName: Prometheus
  grafanaCom:
    id: 22695
