---
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: hello-world-ext-authz
  namespace: istio-ingress
  annotations:
    argocd.argoproj.io/sync-wave: "31"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: Gateway
    name: main-gateway
  action: CUSTOM
  provider:
    name: request-interceptor-provider
  rules:
    - to:
        - operation:
            hosts:
              - hello-world-app.{{ .Values.baseDns }}
