---
apiVersion: v1
kind: Service
metadata:
  name: netshoot
  namespace: example-apps
  annotations:
    argocd.argoproj.io/sync-wave: "33"
spec:
  clusterIP: None
  selector:
    app: netshoot
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: netshoot
  namespace: example-apps
  annotations:
    argocd.argoproj.io/sync-wave: "34"
spec:
  serviceName: netshoot
  replicas: 1
  selector:
    matchLabels:
      app: netshoot
  template:
    metadata:
      labels:
        app: netshoot
    spec:
      restartPolicy: Always
      containers:
        - name: netshoot
          image: nicolaka/netshoot:latest
          command:
            - sleep
            - infinity
