---
apiVersion: v1
kind: Namespace
metadata:
  name: kuadrant-system
  annotations:
    argocd.argoproj.io/sync-wave: "13"
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: kuadrant
  namespace: kuadrant-system
  annotations:
    argocd.argoproj.io/sync-wave: "13"
spec:
  upgradeStrategy: Default
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: rhcl-operator
  namespace: kuadrant-system
  annotations:
    argocd.argoproj.io/sync-wave: "13"
spec:
  channel: stable
  installPlanApproval: Automatic
  name: rhcl-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  config:
    env:
    - name: ISTIO_GATEWAY_CONTROLLER_NAMES
      value: istio.io/gateway-controller
---
apiVersion: kuadrant.io/v1beta1
kind: Kuadrant
metadata:
  name: kuadrant
  namespace: kuadrant-system
  annotations:
    argocd.argoproj.io/sync-wave: "14"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  observability:
    enable: true
